#!/bin/bash

TIMESTEP="10656"

mkdir "fwd_${TIMESTEP}"

cp ../input_agulhas/* fwd_${TIMESTEP}/

sed -i "s/.*offlineIter0.*/ offlineIter0=${TIMESTEP},/" fwd_${TIMESTEP}/data.off

cd "fwd_${TIMESTEP}"

sbatch batch.sh 

cd ..

mkdir "back_${TIMESTEP}"

cp ../input_agulhas/* back_${TIMESTEP}/

sed -i "s/.*runFwd.*/ runFwd=-1,/" back_${TIMESTEP}/data.off

sed -i "s/.*offlineIter0.*/ offlineIter0=${TIMESTEP},/" back_${TIMESTEP}/data.off

cd "back_${TIMESTEP}"

sbatch batch.sh

cd ..
